src/main/java/com/togedog/TogeDogApplication.java, src/main/java/com/togedog/matching/Match.java, src/test/java/com/togedog/matching/MatchTest.java
=> feat: match 테이블 만들기

src/main/java/com/togedog/audit/Auditable.java
=> feat:#36 Auditable 클래스 생성

src/main/java/com/togedog/dto/MultiResponseDto.java, src/main/java/com/togedog/dto/PageInfo.java, src/main/java/com/togedog/dto/SingleResponseDto.java, src/main/java/com/togedog/exception/BusinessLogicException.java, src/main/java/com/togedog/exception/ExceptionCode.java, src/main/java/com/togedog/utils/UriCreator.java
=> fix:#39 excpetion 버그 수정

src/main/java/com/togedog/board/dto/BoardDto.java, src/main/java/com/togedog/board/entity/Board.java
=> feat:#12 Super Table Board Entity,Dto 구현

src/main/java/com/togedog/matching/dto/MatchingDto.java, src/main/java/com/togedog/matching/entity/Matching.java
=> feat:#33 matching Entity, Dto 구현

src/main/java/com/togedog/exception/ExceptionCode.java, src/main/java/com/togedog/member/controller/MemberController.java, src/main/java/com/togedog/member/dto/MemberDto.java, src/main/java/com/togedog/member/mapper/MemberMapper.java, src/main/java/com/togedog/member/member/Member.java, src/main/java/com/togedog/member/repository/MemberRepository.java, src/main/java/com/togedog/member/service/MemberService.java
=> feat:#24, #25, #26, #27, #43 회원 패키지 구현

src/main/java/com/togedog/match/controller/MatchController.java, src/main/java/com/togedog/match/repository/MatchRepository.java, src/main/java/com/togedog/match/service/MatchService.java
=> fix:#46 매칭 mapping & Repository method 오류 수정

build.gradle, src/main/java/com/togedog/auth/dto/LoginDto.java, src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/togedog/auth/filter/JwtVerificationFilter.java, src/main/java/com/togedog/auth/jwt/JwtTokenizer.java, src/main/java/com/togedog/auth/userdetails/MemberDetailsService.java, src/main/java/com/togedog/auth/utils/CustomAuthorityUtils.java, src/main/java/com/togedog/config/SecurityConfiguration.java, src/main/java/com/togedog/member/member/Member.java, src/main/java/com/togedog/member/service/MemberService.java
=> feat:#52 Security 권한 부여 기능 구현

src/main/java/com/togedog/friend/controller/FriendController.java, src/main/java/com/togedog/friend/mapper/FriendMapper.java, src/main/java/com/togedog/friend/service/FriendService.java, src/main/java/com/togedog/member/entity/Member.java, src/main/java/com/togedog/pet/dto/PetDto.java, src/main/java/com/togedog/pet/entity/Pet.java
=> feat:#72 반려동물entity/dto구현

src/main/java/com/togedog/auth/dto/LoginDto.java, src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/togedog/auth/filter/JwtVerificationFilter.java, src/main/java/com/togedog/auth/handler/MemberAccessDeniedHandler.java, src/main/java/com/togedog/auth/handler/MemberAuthenticationEntryPoint.java, src/main/java/com/togedog/auth/handler/MemberAuthenticationFailureHandler.java, src/main/java/com/togedog/auth/handler/MemberAuthenticationSuccessHandler.java, src/main/java/com/togedog/auth/utils/ErrorResponder.java, src/main/java/com/togedog/board/repository/BoardRepository.java, src/main/java/com/togedog/config/SecurityConfiguration.java, src/main/java/com/togedog/errorResponse/ErrorResponse.java
=> feat:#11 JWT 발행 기능

src/main/java/com/togedog/audit/Auditable.java, src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/togedog/exception/ExceptionCode.java, src/main/java/com/togedog/matching/controller/MatchingController.java, src/main/java/com/togedog/matching/dto/MatchingDto.java, src/main/java/com/togedog/matching/entity/Matching.java, src/main/java/com/togedog/matching/mapper/MatchingMapper.java, src/main/java/com/togedog/matching/repository/MatchingRepository.java, src/main/java/com/togedog/matching/service/MatchingService.java
=> fix:#46 matching restapi변경

src/main/java/com/togedog/config/SecurityConfiguration.java, src/main/java/com/togedog/exception/ExceptionCode.java, src/main/java/com/togedog/matching/controller/MatchingController.java, src/main/java/com/togedog/matching/dto/MatchingDto.java, src/main/java/com/togedog/matching/entity/Matching.java, src/main/java/com/togedog/matching/mapper/MatchingMapper.java, src/main/java/com/togedog/matching/service/MatchingService.java, src/main/java/com/togedog/matchingStandBy/controller/MatchingStandByController.java, src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java, src/main/java/com/togedog/matchingStandBy/entity/MatchingStandBy.java, src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java, src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java, src/main/java/com/togedog/matchingStandBy/service/MatchingStandByService.java, src/main/java/com/togedog/member/entity/Member.java
=> feat:#89 matchingStandBy 구현

src/main/java/com/togedog/config/SecurityConfiguration.java
=> fix:#52 Cors config 수정

src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java
=> fix:#89 Post Dto 누락 수정

src/main/java/com/togedog/auth/controller/AuthController.java, src/main/java/com/togedog/auth/dto/RedisProperties.java, src/main/java/com/togedog/auth/service/AuthService.java, src/main/java/com/togedog/email/config/EmailConfig.java, src/main/java/com/togedog/email/config/RedisConfig.java, src/main/java/com/togedog/email/service/EmailVerificationService.java, src/main/java/com/togedog/email/tool/EmailTool.java, src/main/java/com/togedog/email/tool/RedisTool.java, src/main/java/com/togedog/member/dto/VerificationRequest.java
#115, #114, #113, #112, #118, #123, #124, #54, #83
=> feat:#115, #114, #113, #112, #118, #123, #124, #54, #83

src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java, src/main/java/com/togedog/chatRoom/dto/ChatRoomDto.java, src/main/java/com/togedog/chatRoom/entity/ChatRoom.java, src/main/java/com/togedog/chatRoom/entity/ChatRoomMember.java, src/main/java/com/togedog/chatRoom/mapper/ChatRoomMapper.java, src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java, src/main/java/com/togedog/chatRoom/service/ChatRoomService.java, src/main/java/com/togedog/eventListener/EventCaseEnum.java, src/main/java/com/togedog/eventListener/ServiceEventListener.java, src/main/java/com/togedog/matchingStandBy/service/MatchingStandByService.java, src/main/java/com/togedog/member/entity/Member.java, src/main/java/com/togedog/member/repository/MemberRepository.java, src/main/java/com/togedog/member/service/MemberService.java
=> feat:#34 chatRoom 구현

build.gradle, src/main/java/com/togedog/chat/config/WebSocketConfig.java, src/main/java/com/togedog/chat/controller/ChatController.java, src/main/java/com/togedog/chat/dto/ChatMessageDto.java, src/main/java/com/togedog/chat/entity/ChatMessage.java, src/main/java/com/togedog/chat/service/ChatService.java, src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java, src/main/java/com/togedog/chatRoom/repository/ChatRoomMemberRepository.java, src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java, src/main/java/com/togedog/config/SecurityConfiguration.java
=> feat:#138 chat package 추가

src/main/java/com/togedog/email/service/EmailVerificationService.java, src/main/java/com/togedog/matching/service/MatchingService.java
=> fix:#33 matching create 중복에 대한 처리 방식 변경

src/main/java/com/togedog/board/controller/BoardController.java, src/main/java/com/togedog/board/dto/BoardDto.java, src/main/java/com/togedog/board/entity/Board.java, src/main/java/com/togedog/board/entity/BoardAnnouncement.java, src/main/java/com/togedog/board/entity/BoardInquiry.java, src/main/java/com/togedog/board/mapper/BoardMapper.java, src/main/java/com/togedog/board/repository/BoardRepository.java, src/main/java/com/togedog/board/service/BoardService.java, src/main/java/com/togedog/friend/controller/FriendController.java, src/main/java/com/togedog/member/controller/MemberController.java, src/main/java/com/togedog/member/dto/MemberDto.java, src/main/java/com/togedog/member/entity/Member.java, src/main/java/com/togedog/member/mapper/MemberMapper.java, src/main/java/com/togedog/member/repository/MemberRepository.java, src/main/java/com/togedog/member/service/MemberService.java
=> feat:#150, #149 게시판 CRUD 수정, 아이디찾기 기능, 회원가입Api 분리

src/main/java/com/togedog/chat/entity/Chat.java, src/main/java/com/togedog/chat/mapper/ChatMapper.java, src/main/java/com/togedog/chat/repository/ChatRepository.java, src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java, src/main/java/com/togedog/chatRoom/dto/ChatRoomDto.java, src/main/java/com/togedog/chatRoom/mapper/ChatRoomMapper.java, src/main/java/com/togedog/chatRoom/repository/ChatRoomMemberRepository.java, src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java, src/main/java/com/togedog/chatRoom/service/ChatRoomService.java, src/main/java/com/togedog/dto/MultiResponseDto.java, src/main/java/com/togedog/matching/controller/MatchingController.java, src/main/java/com/togedog/matching/repository/MatchingRepository.java, src/main/java/com/togedog/matching/service/MatchingService.java
=> feat:#138 채팅 조회 기능 구현

src/main/java/com/togedog/eventListener/EventCaseEnum.java, src/main/java/com/togedog/eventListener/ServiceEventListener.java, src/main/java/com/togedog/matching/service/MatchingService.java, src/main/java/com/togedog/member/controller/MemberController.java, src/main/java/com/togedog/redis/MarkerService.java
=> feat:#46 matching - marker 연결관계 설정

src/main/java/com/togedog/board/dto/BoardDto.java, src/main/java/com/togedog/board/entity/Board.java, src/main/java/com/togedog/board/entity/BoardInquiry.java, src/main/java/com/togedog/board/mapper/BoardMapper.java, src/main/java/com/togedog/comment/dto/CommentDto.java, src/main/java/com/togedog/comment/entity/Comment.java, src/main/java/com/togedog/exception/ExceptionCode.java, src/main/java/com/togedog/member/entity/Member.java, src/main/java/com/togedog/reply/controller/ReplyController.java, src/main/java/com/togedog/reply/dto/ReplyDto.java, src/main/java/com/togedog/reply/entity/Reply.java, src/main/java/com/togedog/reply/mapper/ReplyMapper.java, src/main/java/com/togedog/reply/repository/ReplyRepository.java, src/main/java/com/togedog/reply/service/ReplyService.java
대댓글 기능 구현
Member,Comment,Board,Reply 연관관계 설정
게시물 조회시 대댓글도 조회 가능
=> feat:#162 대댓글 기능 구현

src/main/java/com/togedog/matching/controller/MatchingController.java, src/main/java/com/togedog/matching/dto/MatchingDto.java, src/main/java/com/togedog/matching/mapper/MatchingMapper.java, src/main/java/com/togedog/matching/repository/MatchingRepository.java, src/main/java/com/togedog/matching/service/MatchingService.java
=> feat:#46 matching - marker 회원 조회 기능 구현

src/main/java/com/togedog/matching/controller/MatchingController.java, src/main/java/com/togedog/matching/entity/Matching.java, src/main/java/com/togedog/matching/mapper/MatchingMapper.java, src/main/java/com/togedog/matching/repository/MatchingRepository.java, src/main/java/com/togedog/matching/service/MatchingService.java, src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java, src/main/java/com/togedog/matchingStandBy/entity/MatchingStandBy.java, src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java, src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java
=> fix:#46 matching 현황 조회 기능 오류 수정

src/main/java/com/togedog/matchingStandBy/controller/MatchingStandByController.java, src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java, src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java, src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java, src/main/java/com/togedog/matchingStandBy/service/MatchingStandByService.java
=> fix:#46 matching - front 연결 이슈 수정
